In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('data.csv')

In [5]:
df.head()

fever  bodyPain  Age  runnyNose  diffBreath  cough  infected_prob
0     98         0   16          0           1      0              0
1     99         1   18          0           0      1              0
2    100         0   56          1           0      1              1
3    101         1   24          0          -1      1              1
4    102         1   22          1           1      0              0

In [6]:
df.tail()

fever  bodyPain  Age  runnyNose  diffBreath  cough  infected_prob
3    101         1   24          0          -1      1              1
4    102         1   22          1           1      0              0
5    103         1   67          1           1      1              1
6    101         0   12          0           1      0              0
7    103         1   23          1           1      0              1

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   fever          8 non-null      int64
 1   bodyPain       8 non-null      int64
 2   Age            8 non-null      int64
 3   runnyNose      8 non-null      int64
 4   diffBreath     8 non-null      int64
 5   cough          8 non-null      int64
 6   infected_prob  8 non-null      int64
dtypes: int64(7)
memory usage: 576.0 bytes


In [8]:
df['diffBreath'].value_counts()

 1    5
 0    2
-1    1
Name: diffBreath, dtype: int64

In [9]:
df.describe()

fever  bodyPain        Age  runnyNose  diffBreath     cough  \
count    8.000000  8.000000   8.000000   8.000000    8.000000  8.000000   
mean   100.875000  0.625000  29.750000   0.500000    0.500000  0.500000   
std      1.807722  0.517549  20.204314   0.534522    0.755929  0.534522   
min     98.000000  0.000000  12.000000   0.000000   -1.000000  0.000000   
25%     99.750000  0.000000  17.500000   0.000000    0.000000  0.000000   
50%    101.000000  1.000000  22.500000   0.500000    1.000000  0.500000   
75%    102.250000  1.000000  32.000000   1.000000    1.000000  1.000000   
max    103.000000  1.000000  67.000000   1.000000    1.000000  1.000000   

       infected_prob  
count       8.000000  
mean        0.500000  
std         0.534522  
min         0.000000  
25%         0.000000  
50%         0.500000  
75%         1.000000  
max         1.000000

# Train test splitting

In [10]:
import numpy as np

In [11]:
def data_split(data,ratio):
    np.random.seed(42)
    shuffled = np.random.permutation(len(data))
    test_set_size = int(len(data) * ratio)
    test_indices = shuffled[:test_set_size]
    train_indices = shuffled[test_set_size:]
    return data.iloc[train_indices], data.iloc[test_indices]

In [12]:
np.random.permutation(6)

array([5, 2, 4, 1, 0, 3])

In [13]:
train , test = data_split(df,0.2)

In [14]:
train

fever  bodyPain  Age  runnyNose  diffBreath  cough  infected_prob
5    103         1   67          1           1      1              1
0     98         0   16          0           1      0              0
7    103         1   23          1           1      0              1
2    100         0   56          1           0      1              1
4    102         1   22          1           1      0              0
3    101         1   24          0          -1      1              1
6    101         0   12          0           1      0              0

In [15]:
test

fever  bodyPain  Age  runnyNose  diffBreath  cough  infected_prob
1     99         1   18          0           0      1              0

In [21]:
X_train = train[['fever','bodyPain','Age','runnyNose','diffBreath','cough']].to_numpy()
X_test = test[['fever','bodyPain','Age','runnyNose','diffBreath','cough']].to_numpy()

In [22]:
Y_train = train[['infected_prob']].to_numpy().reshape(7,)
Y_test = test[['infected_prob']].to_numpy().reshape(1,)


In [23]:
Y_train

array([1, 0, 1, 1, 0, 1, 0])

In [24]:
from sklearn.linear_model import LogisticRegression

In [27]:
clf = LogisticRegression()
clf.fit(X_train,Y_train)

LogisticRegression()

In [38]:
input =[100,1,34,1,0,1]
clf.predict([input])

array([1])

In [29]:
clf.predict_proba([[100,1,34,1,0,1]])

array([[4.00851229e-04, 9.99599149e-01]])

In [33]:
inf = clf.predict([[100,1,34,1,0,1]])

In [34]:
infProb = clf.predict_proba([[100,1,34,1,0,1]])[0][1]

In [35]:
inf

array([1])

In [37]:
infProb

0.9995991487707241